sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t silvamateus/docker-react .
script:
  - docker run silvamateus/docker-react env CI=true yarn test
deploy:
  provider: heroku
  api_key:
    secure: xnDkN9T+Jq6qi0NalbrthhBRJQTdSGURRITbuwrckTmbsy4OKPJRT+p74yMmeb3riO1ktYqy/ncYJ2a5mtaCAU27ZhlRQ3hNfxAK6iiCkzM7MSPsMYTdcAhfB2roUN5CkCUqThClomWd39PzPO/ir+gHdcP8hfWKLnXsT2pwwgmud+UXrbSZuIR5mGHArnu02RTXTHEOLLxX1ihIzybmfiHA2VBtOb2ZODlltI1PFxhkNUfxIUTqNEdcwen8ojMjtX8CMfMoiUEqefxOQjdGgwq8u+gW4ADkzvofHw2aRd8g/jWzFeDBzgYDM6qzGLN1pwc74N7CBVyiYdLcZsIEawc48t5Ia5mbDU54AdvXEppCqViq2o3b7xjjYcmNjlmQMOlVmH9/stOeHj2zRtJOSLV9pB8nh6iQ9HiXDNLWCe/mJM+S7XllXgpAZGpbCPIqJr5udeir1A2wqJVgBjAPRczLGazzB4QTN6W05OnvgZeJRAWkJEeZF4gZMDAYlsX28cp4/r8IxvjHJevVoPU+wydGuahY1QWJ61dtFy8HKZNmeXNsM9X2UTF00ZF+4wwYaYvoAfDKhJXpbDoQmMyKnHLp6pVdtnzX3nHbQEPi27zt04uXUzK1+y93PRI4uGw+27hGRh0+fvbrMS8TCGE8xYhjBIXqPuG1vuk6s5HiAA4=
  app: silvamateus-docker-react
  on: main
