sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t silvamateus/docker-react .
script:
  - docker run silvamateus/docker-react env CI=true yarn test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: silvamateus-docker-react
  on: main
